### PR TITLE
2.1 lesson

### PR DESCRIPTION
**Pull request by aigerimkwon**

### CODE REVIEW

**Comment by aigerimkwon** [comment]
made mistake

**Comment by tsbrun** [comment]
Looks good, Aigerim 👍🏽 

For future reference, a good process for submitting assignments is to upload to Github (`git add`, `git commit -m`, `git push`) then open a pull request and wait for review. After it's been approved, you can merge the pull request into `main` and delete the branch.  

This isn't a hard and fast rule, but it helps keep your code organized and makes sure that you don't merge any broken code. You don't have to worry about that just yet, but it's good to know for the future.

Good work. Keep at it!

**Comment by nhlmg93** [comment]
not sure what is going on here

**Review by tiwgeetanjali — COMMENTED** [review]
RE: Intro: Lesson 2.1 - Introduction to Git assignment submission
HTML file creation look fine.

**Comment by peterntiamoah** [comment]
Nice work on both lesson 2-1 and 3-1! One friendly reminder that when you create Pull Requests, to set the main for your local repository and not the Code the Dream repo. Good job!

**Pull request closed without merging**
